### ISSUE TITLE
Simpler way to create objects defining an interface

### ISSUE THREAD

**Issue by speth** [Cantera/enhancements#103]
**Abstract**

The currently-available methods for instantiating the set of `ThermoPhase` and `Kinetics` objects defining an interface is somewhat tedious, especially in C++. With appropriate information included in the input file, this could be simplified to a single function call to construct all of the objects and link them together.

**Motivation**

In C++, constructing a surface and its adjoining bulk phases requires something like the following:
```cxx
shared_ptr<Solution> gas = newSolution("diamond.yaml", "gas");
shared_ptr<Solution> bulk = newSolution("diamond.yaml", "diamond");
shared_ptr<Solution> surfSoln = newSolution("diamond.yaml", "diamond_100", "None", {gas, solid});
auto surf = std::dynamic_pointer_cast<SurfPhase>(soln->thermo());
auto surfKin = std::dynamic_pointer_cast<InterfaceKinetics>(soln->kinetics());
```
Where the two somewhat arcane `dynamic_pointer_cast` calls are required in the relatively common case where the user needs to access methods that are defined only on these derived classes, e.g. `setCoverages` and `advanceCoverages`. This is not to mention some of the more convoluted and fragile ways of initializing surface phase objects which litter the test suite.

**Possible Solutions**

The removal of the old `Interface` class in Cantera 2.5 paves the way for a new `Interface` class that follows the structure of the `Solution` class and is not tied to a specific phase model for the surface phase (e.g. providing flexibility to use a non-ideal surface phase model as planned in #59). For this class the `thermo()` and `kinetics()` would return `shared_ptr<SurfPhase>` and `shared_ptr<InterfaceKinetics>`, respectively, removing the need for the user to invoke `dynamic_pointer_cast`.

We could also go a step further and include information in the YAML definition of the surface phase which specifies where the adjacent phases are defined in order to instantiate all of the phases at once. (While this information was included in CTI files, it was used only to require that these adjacent bulk phases were present during construction, but not to actually help construct them.)
For example:
```yaml
phases:
- name: diamond_100
  adjacent-phases: [gas, diamond]
  ...
- name: gas
  ...
- name: diamond
  ...
```

Then, we could define the `newInterface` function so that the only required parameters were the input file name and the (optional) phase name. There are a couple of options for what to do with the adjacent phases. Perhaps the best would be to store those `Solution` objects as part of the `Interface` object. For example:
```c++
shared_ptr<Interface> surf = newInterface("diamond.yaml", "diamond_100");
shared_ptr<ThermoPhase> gas = surf->adjacent(0)->thermo();
shared_ptr<ThermoPhase> bulk = surf->adjacent("diamond")->thermo(); // accessible by name or index
```

In the case where the additional phase names were not in the input file (or where the user wanted to override those values), they could also be provided as an additional argument to the `newInterface` function.

A few other thoughts:
- It would probably make sense to extend this idea to an `Edge` class as well, since instantiating the set of phases involved is even more complicated, with up to 3 bulk phases and 3 interfaces involved.
- For the Python module, adding this should be pretty simple, as the generic `Interface` class already exists, and importing the adjacent phases could be done as part of the constructor for that class. One issue here would be how to transition, given that the `Interface` constructor doesn't currently import those phases.

**References**
* Originally brought up in the context of Cantera/cantera#1062
* #59

**Comment by ischoegl** [comment]
👍 … looks great. The `adjacent` idea follows an existing keyword for the `Solution` constructor in Python, so it looks like a logical extension. I also thought of a `Solution::addAdjacent` earlier today, where you could add an adjacent `Solution` phase.

**Comment by decaluwe** [comment]
Thanks, @speth. In general, I like this a lot.

For the adjacent phases, does the `surf->adjacent(0)->thermo();` return the full phase object (transport and kinetics, as well), or would those have to be done separately?

From a use case perspective, what I'd like to be able to do, e.g. from the Python interface, is something akin to (using your example phases from above):

`surf, gas, bulk = ct.Interface("diamond.yaml", "diamond_100", "gas", "diamond")`

where the order of the adjacent phase inputs matches the order of the returned phase objects.  If we want, we could keep it more similar to the current method, to discriminate between the adjacent and interface phase:

`surf, gas, bulk = ct.Interface("diamond.yaml", "diamond_100", ["gas", "diamond"])`

where now the inputs to the square brackets are phase names in the input, rather than already instantiated phase objects.  I don't know if there are issues with the fact that `Interface` now returns a non-fixed number of objects?  If so, maybe a `dict` or `tuple` could help get around that?

I don't know that any of this contradicts your vision above; my main concern as a user is that I would want the full phase objects returned.

**Comment by speth** [comment]
> For the adjacent phases, does the `surf->adjacent(0)->thermo();` return the full phase object (transport and kinetics, as well), or would those have to be done separately?

I guess I was trying to be too clever in my description. The idea is that `surf->adjacent(0)` is a `Solution` object that includes a `ThermoPhase` object and optionally `Kinetics` and `Transport` objects that can be accessed with the `thermo()`, `kinetics()`, and `transport()` getters, as normal.

> From a use case perspective, what I'd like to be able to do, e.g. from the Python interface, is something akin to (using your example phases from above):
> 
> `surf, gas, bulk = ct.Interface("diamond.yaml", "diamond_100", "gas", "diamond")`

I hadn't I like this function signature, with a couple of caveats. One, it needs to be an independent function, since the constructor for the `Interface` class can only return an `Interface` object. Maybe something like `create_interface` would work. Second, I would like to make specifying the phase names optional, if the relevant information is present in the input file as described above. That way, if the surface phase is listed first there, you could actually do something as simple as:

```python
surf, gas, bulk = ct.create_interface("diamond.yaml")
```
I think it would also make sense to make those phases accessible from the `surf` object in a manner analogous to what I suggested for the C++ interface, e.g. `surf.adjacent("diamond")` would return the bulk `Solution` object.

**Comment by ischoegl** [comment]
After spending some time on a closely related issue (PR Cantera/cantera#1129, which replaces the custom initialization done in Python with C++ `newSolution`), I think getting this implemented would be fairly straight-forward. I agree with @speth insofar as this should be done in C++ (which would be easy once the custom Python constructors are gone). 

To incorporate @decaluwe's Python API request in the original suggestion, all that is needed is to implement an alternate
```C++
shared_ptr<Solution> newInterface(const std::string& infile,
                                  const std::string& name,
                                  const std::vector<std::string>& adjacent={});
```
and look for the `adjacent-phases` entry in YAML with the `adjacent` parameter acting as an override (this is in almost exact analogy to the - already in place and working - `newSolution`). The phases are subsequently created in C++ rather than passing them through the interface (as in the current implementation). As in @speth's original suggestion, we'd have to store adjacent `Solution` objects and make them accessible using something like
```C++
std::vector<shared_ptr<Solution>>& Solution::adjacent
``` 
as the simplest (which is what we currently use for `newSolution`). The initial suggestion at the top would presumably refine this by storing the adjacent phases using a `std::map<std::string, shared_ptr<Solution>>`.

After that, the Python API should be :cake:. It could be as simple as 
```Python
surf = ct.Interface("diamond.yaml", "diamond_100", adjacent=["gas", "diamond"])
gas, bulk = surf.adjacent
```
Note that at the moment, C++ objects do not forward any operations specific to phases, kinetics or transport (they just tie objects together as a 'root' object). As such, there is no need to differentiate between `Solution` or `Interface` in C++ itself.

**Comment by speth** [comment]
> As such, there is no need to differentiate between `Solution` or `Interface` in C++ itself.

While the differentiation is not strictly necessary, my rationale for differentiating between `Solution` and `Interface` was given in the original enhancement proposal:

> For this class the `thermo()` and `kinetics()` would return `shared_ptr<SurfPhase>` and `shared_ptr<InterfaceKinetics>`, respectively, removing the need for the user to invoke `dynamic_pointer_cast`[...] in the relatively common case where the user needs to access methods that are defined only on these derived classes, e.g. `setCoverages` and `advanceCoverages`.

**Comment by ischoegl** [comment]
> While the differentiation is not strictly necessary, my rationale for differentiating between Solution and Interface was given in the original enhancement proposal [...]

I can see that from the perspective of the current framework. The alternative would be to define `setCoverages` and `advanceCoverages` at the `Kinetics` level and throw `NotImplementedErrors` as appropriate (there may be some other methods). We already do that for other objects; this would imho be a way to reign in the outlier implementations specific to `InterfaceKinetics` (see #92). The alternative would be to start working towards a `BulkPhase` to achieve symmetry: i.e. `SurfPhase`/`InterfaceKinetics` and `BulkPhase`/`BulkKinetics`. There are certainly good arguments for avoiding clutter at the base level (see `TransportBase` :wink:).

**Comment by ischoegl** [comment]
Re-opening as a reminder to update the corresponding YAML tutorial on [Cantera/cantera-website](https://cantera.org/tutorials/yaml/defining-phases.html).
