### ISSUE TITLE
Science section re-org

### ISSUE THREAD

**Issue by decaluwe** [Cantera/enhancements#146]
**Abstract**
I'd like to document my thoughts for next steps in reorganizing the website's `Science` section.  

1. Add some more content to the `Transport` landing page.  My sense is that we can cover what we need to on a single page, without going into separate `phase` and `species` pages like we do for thermo, and without adding any other structure (e.g. cards), but we'll see, once it is in place.
2. I plan to populate the `phase-thermo`, `species-thermo`, and `kinetics` pages with a bit more structure so that visitors to the website can more easily navigate to find what they want.  My current plan is to use cards.  
 Once item 2 is in place, resolving issues such as https://github.com/Cantera/cantera-website/issues/169, https://github.com/Cantera/cantera-website/issues/172, or https://github.com/Cantera/cantera-website/pull/174  should be pretty straightforward.
3. This will also require some higher-level thinking about a) how to organize the content, and b) looking at the thermo models and deciding if there are any we want to drop (due to redundant functionalities, for example).  as mentioned in #6.
A brief description of the work being done.

**Motivation**

Describe the need for the work being done:

* Prominent users have noted that it is incredibly difficult, at present, to find any documentation of the scientific theory applied in the Cantera classes.
* At present, the easiest method for this is to scan the source code itself and locate the correct equations.  This is both challenging to do, and an unnecessary hurdle.

**Description**

* The changes here will provide a convenient way for users to inspect and understand the theory that is applied in the codebase.  Ideally, the details will link to the codebase and other implementation details, as appropriate.
* The first step involves a reformatting of the science section, to define and provide a structure for the significant amount of detail that this will entail.

**References**
The just merged https://github.com/Cantera/cantera-website/pull/179 is the first step in this process.

**Comment by speth** [comment]
I meant to comment on this in the previous PR, but one aspect of this that I would like to improve is that with this anticipated layout, it takes a lot of navigation to get from the homepage to the documentation for a specific phase model. That is, you have:

Cantera.org -> Science -> Thermodynamics -> (scroll down) Phases -> Specific Model

There are two options of shortening this by one level that I can think of:
1. Eliminate the "Phases" and "Species" pages below the "Thermodynamics" page and just put the cards for specific models into two subsections on the "Thermodynamics" page.
2. Put direct links to the "Phases" and "Species" page in the "Thermodynamics" card on the "Science" page. This would be similar to the direct links to the Python and Matlab examples that we have within the "Examples" card on the home page.

I think this second option might be better since it still leaves keeps "Phases" and "Species" pages available that can be used to explain some of the concepts that are general across multiple phase / species models.

**Comment by decaluwe** [comment]
Thanks, @speth - this is a great point.  

I'll keep it in mind to see if there are placed to flatten the page structure a bit.  In some cases, I think I can use cards at the top as links to a specific section, but keep the info on the same page so that a user can also just scroll down, if they already know where to look.

(side note: not sure how this ended up in `enhancements`, rather than `cantera-website`...  🤷🏻‍♂️.  But it certainly clears up why the issue and PR numbers weren't linking like I thought they should, in my issue message, above 😂)

**Comment by speth** [comment]
With the recent website reorganization (in particular https://github.com/Cantera/cantera/pull/1647), I'd argue this is effectively complete. If there additional thoughts on how to better organize the "Science" docs, I think it would make sense to describe that in a new enhancement proposal. There is, of course, still plenty of room for expanding on the _content_ of the science documentation, but I think that's covered by some of the other enhancement proposals.
