### ISSUE TITLE
Support SUNDIALS 6.2 features

### ISSUE THREAD

**Issue by bryanwweber** [Cantera/enhancements#148]
**Abstract**

SUNDIALS 6.2 was [just released](https://github.com/LLNL/sundials/releases/tag/v6.2.0) and it has a few features that look interesting.

Specifically:

1. > Added functions to CVODE, CVODES, IDA, and IDAS to change the default step size
adaptivity parameters.

   would be useful to expose to users for setting
2. > Added support to CVODES for integrating IVPs with constraints using BDF methods

   sounds like it _might_ be useful in the sense that we have a constraint on the temperature, density, and mass/mole fractions for certain classes of problems.

We should implement these if it makes sense!

**Comment by speth** [comment]
Regarding (1), before worrying about adding a user interface for these, I think you'd want to see how much tweaking these settings affects the overall speed of integration, and if the optimal values vary for different problems.

Regarding (2), This is a feature that's been around in regular CVODE (non-sensitivity version) for a long time, and the [same general advice is provided](https://sundials.readthedocs.io/en/latest/cvodes/Usage/SIM.html#advice-on-controlling-unphysical-negative-values), with the conclusion "However, because this option involves some extra overhead cost, it should only be exercised if the use of absolute tolerances to control the computed values is unsuccessful.". I think Cantera's been fairly successful in doing this, and don't really see a need to make a change.

**Comment by bryanwweber** [comment]
> and the [same general advice is provided](https://sundials.readthedocs.io/en/latest/cvodes/Usage/SIM.html#advice-on-controlling-unphysical-negative-values)

That's a lovely docs page to read! Thanks for the link. I think it would make sense to add a link to that somewhere in the docs for the custom reactor class.

**Comment by ischoegl** [comment]
Tagging Cantera/cantera#1341
