### ISSUE TITLE
Improve Development Roadmap / Release Schedule / etc.

### ISSUE THREAD

**Issue by ischoegl** [Cantera/enhancements#29]
**Abstract**

The current [development roadmap](https://github.com/Cantera/cantera/wiki/Development-Roadmap) does not involve a time line and does not reference release numbers. While individual items are clearly of interest, the roadmap does not provide insights into what areas are being actively worked on, what may be prioritized in the next release, and what is currently in icebox status.

**Motivation**

Describe the need for the proposed change:

* Implement a more regular release schedule
* Improve interaction with user/contributor community

**Possible Solutions**

Update the wiki page, and/or (possibly) create an outline of big ticket items for individual Cantera releases (e.g. for 2.5 ... introduce YAML, etc.). This could be in the form of upcoming release notes, where a reference in the wiki pages would be useful (it took me a while to locate them on the website).

At the moment, I also assume that 2.5.0b0 may be close (hopefully), which presumably will bring a new feature freeze with subsequent testing. It would be helpful to start tags that indicate whether currently pending PR's and issues are being considered for 2.5, will be deferred to 2.6, or are awaiting contributors' responses to reviews. 

PS: A tighter integration of the [Development Roadmap](https://github.com/Cantera/cantera/wiki/Development-Roadmap) with [GSoC Ideas](https://github.com/Cantera/cantera/wiki/GSoC-2020-Ideas) would likewise be useful.

**References**

 * [Development Roadmap](https://github.com/Cantera/cantera/wiki/Development-Roadmap)
 * [user group announcement of Cantera 2.4](https://groups.google.com/forum/?utm_source=digest&utm_medium=email#!searchin/cantera-users/release$202.4$20available%7Csort:date/cantera-users/EGGWU9X6eMQ/fyw9oox5DAAJ)
 * [Release Notes](https://cantera.org/documentation/index.html)
 * [GSoC Ideas](https://github.com/Cantera/cantera/wiki/GSoC-2020-Ideas)

**Comment by bryanwweber** [comment]
A few immediate thoughts...

> I also assume that 2.5.0b0 may be close (hopefully)

Likewise, hopefully! I had really wanted to push this out over winter break, but well, life happened. Nonetheless I agree that a more regular release schedule would largely be beneficial, and 1.5+ years between releases is too long.

> A tighter integration of the Development Roadmap with GSoC Ideas

Probably, most of the Roadmap and the GSoC ideas should move into issues in this repository. Both wiki pages were created at a time when we didn't have this repo, so they haven't been added here yet.

P.S. If you have a domestic grad/undergrad student who needs/wants funding for the summer, we should chat about GSoC project ideas. Send an email if you want.

**Comment by ischoegl** [comment]
> Probably, most of the Roadmap and the GSoC ideas should move into issues in this repository. 

:+1:  ... I added a PR for a GSoC template in #30

**Comment by speth** [comment]
Part of my idea with introducing this "enhancements" repository was for it to be a more dynamic replacement for that rather outdated roadmap. I just haven't had time to convert those items to issues in this repo. Most of them would need to be significantly expanded to match the desired level of detail. Feel free to create new issues here for any of the topics that are still relevant.

Along the same lines, I'm :+1: on making GSoC ideas issues here rather than maintaining a separate list.

I think as we near a release, it is useful to create a Milestone in Github and add relevant issues to that. We've done this for most recent Cantera releases except for 2.4.0. Now is probably a fine time to do that for 2.5.0. I'm not sure how useful it is to do this on a longer time horizon -- my general expectation is that things get added to `master` when they're ready.

**Comment by ischoegl** [comment]
@speth ... thanks for the insights.

> I think as we near a release, it is useful to create a Milestone in Github and add relevant issues to that. We've done this for most recent Cantera releases except for 2.4.0. Now is probably a fine time to do that for 2.5.0.

I think this would be great at this point. :+1:
