### ISSUE TITLE
Clearly separate Species and Reactions when defining Solution objects (Phases)

### ISSUE THREAD

**Issue by ischoegl** [Cantera/enhancements#65]
**Abstract**

~Make reactions independent of phases/species, which will simplify loading of lists of reactions.~ Clearly separate Species and Reactions when defining Solution objects (Phases).

**Motivation**

The current implementation of `Solution` objects has no clear separation of `Phase`, `SpeciesThermo` and `Kinetics`. Phases (which implicitly reference `SpeciesThermo`) are instantiated first and `Kinetics` requires knowledge of phases/species, although reactions themselves have no such dependency. The implementation of `Transport` is an add-on.

In an overhaul, it is conceivable to map the construction of a `Solution` object to the new YAML format: i.e. load `Species` and `Reactions` first, and combine them to a `Phase` last. This change would enable loading of YAML files that only include species definitions (e.g. `nasa.yaml`) or only reactions. As such, it would greatly simplify the construction of mechanisms from components.

**Possible Solutions**

It is conceivable to load a list of species without having to necessarily assign them to a phase; the same holds true for reactions (see discussion on `ct.Reaction.listFromFile` in Cantera/cantera#821). The phase node would then only establish a context as well as link species and reactions, i.e. the `Solution` object would simply combine lists of species and reactions.

The least intrusive change would be to separate species handling from the phase object, and to instantiate the phase object last (instead of first). Kinetics could be instantiated without knowledge of species/phases if the initialization of reactions is deferred to a point after phase(s) are loaded. For heterogeneous reactions, Species/Kinetics could be shared by multiple phases, which would eliminate the need for `InterfaceKinetics`.

An immediate result would be that YAML files like `nasa.yaml` could be loaded directly (which is currently not possible); likewise, it's conceivable to load a YAML file that only contains reactions (which is currently also not possible). From my perspective, this would be more intuitive to new users (i.e. any YAML file can be loaded as a `Solution` object), and hopefully clear up some complex interactions in the C++ code base.

Another result would be that handling of model switches would become more flexible/consistent. I.e. on-the-fly switches of thermo models would be straight-forward and could be done the same way as a switch from `mixture-averaged` to `multi-component` `Transport`. An example is `Redlich-Kwong` vs `ideal-gas` models in `nDodecane_Reitz.yaml`.

**References**

Cantera/cantera#821
Cantera/cantera#910

**Comment by speth** [comment]
I guess I'm a little confused, because much of this is already possible. For instance, you can import all of the species in `nasa.yaml` simply by writing (in Python) `S = ct.Species.listFromFile('nasa.yaml')`, which creates a bunch of `Species` objects that can then be added to phases (or not).

For reactions, there is a significant complication which arises from handling the units of the rate coefficient. The dimensions of the rate coefficient depend on the dimensions of the standard concentrations for each reactant species, which can't be determined without knowing what phase model is being used for that species. Without knowing the dimensions of the rate coefficient, we can't convert the value given in the input file from whatever units are used in the input file to Cantera's internal mks-kmol unit system. The only reason it was possible to create reactions without reference to a `Kinetics` object with CTI/XML is because the XML format required always had the pre-exponential factors for reactions in mks-kmol units. There might be a way around this, but I think it would require a significant refactoring of how we handle the reaction rate parameterizations, and just be shifting complexity there.

That said, it certainly is possible to create `Reaction` objects from a YAML file that only contains reaction definitions, as long as you have created a `Kinetics` object which those reactions could be added to first. This is what the [extract_submechanism.py](https://github.com/Cantera/cantera/blob/main/interfaces/cython/cantera/examples/kinetics/extract_submechanism.py) is meant to demonstrate, if you were to specify such an input file in the call to `ct.Reaction.listFromFile(input_file, ref_phase)`.

> From my perspective, this would be more intuitive to new users (i.e. any YAML file can be loaded as a Solution object)

`Reaction`s and `Species` aren't `Solution`s, so why should `Solution(filename)` do anything other than create a `Solution` object?

> Another result would be that handling of model switches would become more flexible/consistent. I.e. on-the-fly switches of thermo models would be straight-forward and could be done the same way as a switch from `mixture-averaged` to `multi-component` `Transport`. An example is `Redlich-Kwong` vs `ideal-gas` models in `nDodecane_Reitz.yaml`.

I think this would be useful, and is something that could be achieved in the same way as the transport model switching is handled in the Python `Solution` class, where the underlying `ThermoPhase` object would just be deleted and a new one of the appropriate type created. The only additional complexity here that doesn't exist for the transport case is that you then need to link the kinetics and transport objects to the new `ThermoPhase` object, but that's already possible.

**Comment by ischoegl** [comment]
@speth ... thanks for your comments!

> I guess I'm a little confused, because much of this is already possible. 

It sure is! My main point was about the sequence of instantiation, i.e. thermophase - species - kinetics/reactions - transport, which imho creates awkward dependencies. The new YAML structure is much clearer, and it would be nice if it neatly mapped to the code.

> For reactions, there is a significant complication which arises from handling the units of the rate coefficient. The dimensions of the rate coefficient depend on the dimensions of the standard concentrations for each reactant species, which can't be determined without knowing what phase model is being used for that species. 

This would mean that reactions are not portable across mechanisms, as their dimensions are defined elsewhere?!? This is probably historical, but certainly not ideal and limits extensions. Wouldn't it make sense to have a default unit system set using the `units` field at the top level, and let it be overriden either per YAML `equation` entry, or for an entire YAML `reactions` block? Likewise for `species`? That way things have clearly defined reference points and thus can always made be compatible. It's imho a relatively minor change as the consistent unit system can already be inferred by the top-level `units` field.

> Reactions and Species aren't Solutions, so why should Solution(filename) do anything other than create a Solution object?

Point taken - for me as non-native speaker `Solution` is still pretty devoid of meaning - although I certainly know what it is supposed to mean as opposed to its more common usage.

Overall, most of my comments pertain to how things work 'under the hood', so there shouldn't be much that is apparent to the user.

**Comment by speth** [comment]
> Wouldn't it make sense to have a default unit system set using the `units` field at the top level, and let it be overriden either per YAML `equation` entry, or for an entire YAML `reactions` block?

Yes, this is exactly how units are handled in the YAML format. However, note that I specifically mean the *dimensions*, not just the *units* of the rate coefficient, cannot be determined from the reaction equation alone.

> This would mean that reactions are not portable across mechanisms, as their dimensions are defined elsewhere?!?

Yes and no. The first case where this comes up is for reactions involving surface and bulk phase species, where the dimensions of concentration are different for different species, i.e quantity/length^2 versus quantity/length^3. But without phase definitions, there's no way to know which species in a reaction equation are in which phase.

The other case, where reaction parameterizations are indeed not necessarily portable across phase models, is if a different definition of what Cantera calls the "activity concentration" is used, which is the concentration-like terms appearing in the rate expression i.e. `R_f = [A][B]k_f`. While molar concentration is pretty universally in ideal gas combustion models, that's not true across other fields, and these terms could be mole fractions, partial pressures, molalities, etc. (all modified suitably by the activities in the case of non-ideal phases).

**Comment by ischoegl** [comment]
Overall, I don't see the situation very different than a case where a user will have to make sure that species acronyms are consistent (even within the same phase) when combining mechanisms.

I believe there's a middle ground to be found though - generate a list of species and reaction that are aware of their context (within `ct.Species.listFromFile` / `ct.Reaction.listFromFile`, without necessarily instantiating the thermo phase or a kinetics object (and the transport manager if it should exist): as long as a `Reaction` object knows what species mean it's ok to not have `kinetics` instantiated. The current work-around of
```Python
ref_phase = ct.Solution(thermo='ideal-gas', kinetics='gas', species=all_species)
all_reactions = ct.Reaction.listFromFile(input_file, ref_phase)
```
is not really satisfying; there should be a way to simplify this to
```
all_reactions = ct.Reaction.listFromFile(input_file)
```
by making reactions a little more aware of what species actually mean.

However, the main reason of why I created the issue here was the rather convoluted sequence of object instantiation in C++, which the current discussion doesn't really address.

**Comment by bryanwweber** [comment]
> ... as long as a `Reaction` object knows what species mean it's ok to not have `kinetics` instantiated.

I think what @speth is saying is that this isn't the case. A `Reaction` _does_ need to know about `Kinetics` to be able to calculate the dimensions of the forward rate constant. It is not necessarily the case that the dimensions of the concentrations are N/L^3, they can change depending on what phase each reactant is in, and that information is stored in the `Kinetics` object, to facilitate re-use of the reactions.

> However, the main reason of why I created the issue here was the rather convoluted sequence of object instantiation in C++, which the current discussion doesn't really address.

This isn't really clear from the Abstract and the rest of the original post. Your abstract is explicitly about being able to load reactions by themselves from a file... Can you clarify more specifically how the internals could change to simplify things?

**Comment by speth** [comment]
The fact that a reaction has to be aware of it's context is kind of my point. And the way that we provide that context is by having a `Kinetics` object available when constructing the `Reaction` object. Where else would that context come from?

Perhaps a concrete example would help here. Take the second reaction at the triple phase boundary given in `sofc.yaml`:
```yaml
- equation: O(m) + (ox) + 2 electron <=> (m) + O''(ox)  # Reaction 11
  id: edge-f3
  rate-constant: {A: 5.0e+13, b: 0.0, Ea: 120.0}
  beta: 0.5
```
In this reaction, `O(m)` represents an oxygen atom on the metal surface, `(ox)` represents a vacant site on the oxide surface, and `electron` represents a conduction electron in the bulk metal. If we let `C^a_k` be the "activity concentration" for each species, then the forward reaction rate is generically defined as `R_f = C^a_{O(m)} * C^a_{(ox)} * C^a_{electron}^2 * A * exp(-Ea/RT)`. The dimensions and units of `A` are not specified here, but we do know that it's in some combination of cm and mol. To determine the actual dimensions and units, we need to know:
* The units of `R_f`, which we know to be kmol/m/s, since the triple phase boundary, where this reaction takes place, is a one dimensional surface (edge).
* The units of `C^a_{O(m)}` and `C^a_{(ox)}`, which we know to be `kmol/cm^2` since both of these species belong to `ideal-surface` phases
* The units of `C^a_{electron}`, which is dimensionless (and equal to 1), according to the definition of the `electron-cloud` phase.

A complete `Kinetics` object containing all of these species seems like the simplest way to provide all of the necessary information to create a concrete `Reaction` object.

Conceivably, an incomplete `Reaction`-like object could be constructed without this information, where you would carry around the `AnyValue` for the rate constant along with the associated `UnitSystem`, but there would be no way to implement some of the features of the existing `Reaction` class, like the ability to evaluate the rate coefficient or query the parameters of the rate expression, and you would have to defer the full instantiation of the `Reaction` object until it was added to a `Kinetics` object. To me, that seems at least as convoluted as the current implementation.

Maybe this is a matter of perspective, but I don't see the relationship between `Species`, `ThermoPhase`, `Kinetics` and `Reaction` as having that much unnecessary complexity. The `ThermoPhase` and `Kinetics` classes are containers, and you put `Species` and `Reactions` into those containers. What exactly a `Species` in a particular `ThermoPhase` class means depends on both the species and the phase thermodynamic models, and likewise for reactions and kinetics.

**Comment by ischoegl** [comment]
@speth ... thank you for your concluding comments. 

> A complete Kinetics object containing all of these species seems like the simplest way to provide all of the necessary information to create a concrete Reaction object.

I am starting to come around to this perspective, so we can put this to rest.

I believe there still is room for improvement when reading reactions (some things are currently parsed twice), but those are smaller changes that can be discussed elsewhere.

**Comment by speth** [comment]
> The only thing that this approach won’t lend itself to is switching out of thermo models

I don't think there's any technical barrier to switching thermo models. Per the discussion here, the one concern I see is with the standard concentrations, where the same reaction rate expression can't make sense for two different standard concentrations. But that's true regardless of when or how the `Reaction` object is created, and I'd expect this to come up only in rare instances.

> I believe there still is room for improvement when reading reactions (some things are currently parsed twice)

No argument there.

**Comment by ischoegl** [comment]
@speth - truly appreciate your comments! I still don’t see a good way of switching thermo models (everything appears to be pinned to it, so a bunch of stuff would have to be reallocated), but I agree that it’s probably not a priority and the discussion has run its course. While I still believe that what I proposed here is workable, I now agree that it won’t result in making things simpler so it’s not worth pursuing / exploring further.
